[package]
name = "toki-pona"
version = "0.1.0"
edition = "2024"

[dependencies]
chumsky = "0.9.3"
ariadne = "0.4.0"
strum = "0.26"
strum_macros = "0.26"
colored = "3.1.1"
clap = { version = "4.5.54", features = ["derive"] }

[dev-dependencies]
walkdir = "2.5.0"
